Feature autocomplete handler
mucsci-students/2022sp-420-NotJava pull request #218
Opened 2022-03-29 03:30 UTC by mayoung00

2022-03-29 18:59 UTC, gfry99 requested changes
Couple of things I found during my first pass.

1. Make sure to make the documentation uniform, I'm seeing some issues involving capitalization at the beginning of the documentation.
2. There is currently an issue with the way we are printing  the prompt to the user, currently a user is able to hold backspace and delete some characters of the prompts.  Can we do some looking into this issue to find a potential issue.

2022-03-30 21:22 UTC, Robunnin commented on UMLEditor/UMLEditor/Classes/AutoCompleteHandler.cs
> +    public string[] GetSuggestions(string forLine, int index)
Why is there an overload of this method where index and forLine are flipped?

2022-03-30 21:33 UTC, Robunnin commented on UMLEditor/UMLEditor/Classes/AutoCompleteHandler.cs
> +    }
This seems to be using my initial demo implementation, which was a rough proof of concept. A cleaner way to do canidate finding would be to use the index provided in LastMatchinIndex to do size comparisions and String.StartsWith to see if the command is a match. 

For instance, if the user entered 10 characters and a command is 5 you immediately know it isn't a match. If the number of characters is <= the length of the command then if the command starts with the entered text it is a match.
Commands: add_class add_method
User entered add (4 characters)
Both start with add_: **add**_class **add**_method

2022-03-30 21:42 UTC, Robunnin commented
The prompt bugs seems to only happen after a ctrl+backspace, which is supported in Windows shells but doesn't seem to be on bash (I have not tested macOS yet)

2022-03-31 03:10 UTC, Robunnin commented on UMLEditor/UMLEditor/Views/CommandLine/CommandLineController.cs
> -    /// <param name="input">command to execute</param>
The tag for input got deleted in the documentation block

2022-03-31 03:47 UTC, gfry99 approved these changes
Merging, but keep Robert's comment [here](https://github.com/mucsci-students/2022sp-420-NotJava/pull/218/files#r838983817) in mind for a possible refactor.  Currently if a user types in list_ and cycles through possible commands, load_diagram shows up as a potential option.

2022-03-31 03:48 UTC, merged